Update MemberProfileExtension.php
symbiote/silverstripe-memberprofiles pull request #187
Opened 2023-12-18 18:48 UTC by AntonyThorpe

FIX for the unserialize function when passing null to the first parameter.  Thanks.

2023-12-18 19:20 UTC, michalkleiner requested changes

2023-12-18 19:20 UTC, michalkleiner commented on src/Extensions/MemberProfileExtension.php
> +        return (array) unserialize($this->owner->getField('PublicFieldsRaw') '');
```suggestion
        return (array) unserialize($this->owner->getField('PublicFieldsRaw') ?? '');
```

2023-12-19 18:58 UTC, AntonyThorpe commented on src/Extensions/MemberProfileExtension.php
> +        return (array) unserialize($this->owner->getField('PublicFieldsRaw') '');
Thank you.  Have added the missing ?? to the PR.

2024-08-29 08:19 UTC, AntonyThorpe commented
Any feedback please?

2024-09-13 06:13 UTC, nyeholt commented
Handled in #190

2024-09-13 06:13 UTC, closed without merging